<Project Sdk="Uno.Sdk">
	<PropertyGroup>
		<TargetFrameworks>
			net9.0-android;
			net9.0-ios;
			net9.0-maccatalyst;
			net9.0-windows10.0.22621;
			net9.0-desktop;
			net9.0-browserwasm;
		</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<UnoSingleProject>true</UnoSingleProject>

		<!-- Display name -->
		<ApplicationTitle>Event Countdowns</ApplicationTitle>
		<!-- App Identifier -->
		<ApplicationId>dev.mzikmund.eventcountdowns</ApplicationId>
		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<UnoFeatures>
			Hosting;
			Mvvm;
			Configuration;
			Localization;
			Toolkit;
		</UnoFeatures>
		<UnoIconForegroundScale>1</UnoIconForegroundScale>
		<UnoIconForegroundScale Condition="'$(IsAndroid)' == 'true'">0.65</UnoIconForegroundScale>

	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net9.0-browserwasm'">
		<WasmShellEnableIDBFS>true</WasmShellEnableIDBFS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" />
		<PackageReference Include="CommunityToolkit.WinUI.Converters" />
		<PackageReference Include="CommunityToolkit.WinUI.Helpers" />
		<PackageReference Include="LiteDB" />
		<PackageReference Include="MZikmund.Toolkit.WinUI" />
		<PackageReference Include="Plugin.InAppBilling" />
		<PackageReference Include="Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI" Condition="!$(TargetFramework.Contains('windows10'))" />
		<PackageReference Include="Uno.Microsoft.Xaml.Behaviors.WinUI.Managed" Condition="!$(TargetFramework.Contains('windows10'))" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Condition="$(TargetFramework.Contains('windows10'))" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\EventCountdowns.Core\EventCountdowns.Core.csproj" />
	</ItemGroup>

</Project>
