<Project Sdk="Uno.Sdk">
	<PropertyGroup>
		<TargetFrameworks>
			net10.0-android;
			net10.0-ios;
			net10.0-windows10.0.26100;
			net10.0-desktop;
			net10.0-browserwasm;
		</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<UnoSingleProject>true</UnoSingleProject>

		<!-- Display name -->
		<ApplicationTitle>Awaitick</ApplicationTitle>
		<!-- App Identifier -->
		<ApplicationId>dev.mzikmund.awaitick</ApplicationId>
		<!-- Versions -->
		<ApplicationDisplayVersion>0.1.1</ApplicationDisplayVersion>
		<ApplicationVersion>2</ApplicationVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<UnoFeatures>
			Hosting;
			Mvvm;
			Configuration;
			Localization;
			Serialization;
			Toolkit;
			SkiaRenderer;
		</UnoFeatures>

		<UnoIconBackgroundFile>Assets/Icons/icon_transparent.svg</UnoIconBackgroundFile>
		<UnoIconBackgroundFile Condition="'$(IsIOS)' == 'true' or '$(IsAndroid)' == 'true'">Assets/Icons/icon.svg</UnoIconBackgroundFile>

		<UnoIconForegroundScale>1</UnoIconForegroundScale>
		<UnoIconForegroundScale Condition="'$(IsAndroid)' == 'true'">0.65</UnoIconForegroundScale>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net10.0-browserwasm'">
		<WasmShellEnableIDBFS>true</WasmShellEnableIDBFS>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="Platforms\Windows\AppIcon.altform-lightunplated_targetsize-16.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-lightunplated_targetsize-24.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-lightunplated_targetsize-256.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-lightunplated_targetsize-32.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-lightunplated_targetsize-48.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-unplated_targetsize-16.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-unplated_targetsize-24.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-unplated_targetsize-256.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-unplated_targetsize-32.png" />
	  <Content Include="Platforms\Windows\AppIcon.altform-unplated_targetsize-48.png" />
	  <Content Include="Platforms\Windows\AppIcon.scale-100.png" />
	  <Content Include="Platforms\Windows\AppIcon.scale-125.png" />
	  <Content Include="Platforms\Windows\AppIcon.scale-150.png" />
	  <Content Include="Platforms\Windows\AppIcon.scale-200.png" />
	  <Content Include="Platforms\Windows\AppIcon.scale-400.png" />
	  <Content Include="Platforms\Windows\AppIcon.targetsize-16.png" />
	  <Content Include="Platforms\Windows\AppIcon.targetsize-24.png" />
	  <Content Include="Platforms\Windows\AppIcon.targetsize-256.png" />
	  <Content Include="Platforms\Windows\AppIcon.targetsize-32.png" />
	  <Content Include="Platforms\Windows\AppIcon.targetsize-48.png" />
	  <Content Include="Platforms\Windows\LargeTile.scale-100.png" />
	  <Content Include="Platforms\Windows\LargeTile.scale-125.png" />
	  <Content Include="Platforms\Windows\LargeTile.scale-150.png" />
	  <Content Include="Platforms\Windows\LargeTile.scale-200.png" />
	  <Content Include="Platforms\Windows\LargeTile.scale-400.png" />
	  <Content Include="Platforms\Windows\MediumTile.scale-100.png" />
	  <Content Include="Platforms\Windows\MediumTile.scale-125.png" />
	  <Content Include="Platforms\Windows\MediumTile.scale-150.png" />
	  <Content Include="Platforms\Windows\MediumTile.scale-200.png" />
	  <Content Include="Platforms\Windows\MediumTile.scale-400.png" />
	  <Content Include="Platforms\Windows\PackageLogo.scale-100.png" />
	  <Content Include="Platforms\Windows\PackageLogo.scale-125.png" />
	  <Content Include="Platforms\Windows\PackageLogo.scale-150.png" />
	  <Content Include="Platforms\Windows\PackageLogo.scale-200.png" />
	  <Content Include="Platforms\Windows\PackageLogo.scale-400.png" />
	  <Content Include="Platforms\Windows\SmallTile.scale-100.png" />
	  <Content Include="Platforms\Windows\SmallTile.scale-125.png" />
	  <Content Include="Platforms\Windows\SmallTile.scale-150.png" />
	  <Content Include="Platforms\Windows\SmallTile.scale-200.png" />
	  <Content Include="Platforms\Windows\SmallTile.scale-400.png" />
	  <Content Include="Platforms\Windows\SplashScreen.scale-100.png" />
	  <Content Include="Platforms\Windows\SplashScreen.scale-125.png" />
	  <Content Include="Platforms\Windows\SplashScreen.scale-150.png" />
	  <Content Include="Platforms\Windows\SplashScreen.scale-200.png" />
	  <Content Include="Platforms\Windows\SplashScreen.scale-400.png" />
	  <Content Include="Platforms\Windows\WideTile.scale-100.png" />
	  <Content Include="Platforms\Windows\WideTile.scale-125.png" />
	  <Content Include="Platforms\Windows\WideTile.scale-150.png" />
	  <Content Include="Platforms\Windows\WideTile.scale-200.png" />
	  <Content Include="Platforms\Windows\WideTile.scale-400.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" />
		<PackageReference Include="CommunityToolkit.WinUI.Converters" />
		<PackageReference Include="CommunityToolkit.WinUI.Helpers" />
		<PackageReference Include="MZikmund.Toolkit.WinUI" />
		<PackageReference Include="Uno.Microsoft.Xaml.Behaviors.WinUI.Managed" Condition="!$(TargetFramework.Contains('windows10'))" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Condition="$(TargetFramework.Contains('windows10'))" />
		<PackageReference Include="SourceGear.sqlite3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Awaitick.Core\Awaitick.Core.csproj" />
	</ItemGroup>
</Project>
