namespace Awaitick.Core.Models.Licensing;

/// <summary>
/// Third-party components shipped inside Awaitick, grouped by licence.
/// </summary>
/// <remarks>
/// Compiled in rather than loaded from a file or the network, so the notices are
/// available offline and identically on every target. Keep in sync with
/// THIRD-PARTY-NOTICES.md at the repository root.
/// </remarks>
public static class ThirdPartyNotices
{
	public static IReadOnlyList<ThirdPartyNoticeGroup> Packages { get; } =
	[
		new("MIT", "https://opensource.org/license/mit",
		[
			"CommunityToolkit.Common",
			"CommunityToolkit.Mvvm",
			"CommunityToolkit.WinUI.Controls.Primitives",
			"CommunityToolkit.WinUI.Controls.SettingsControls",
			"CommunityToolkit.WinUI.Converters",
			"CommunityToolkit.WinUI.Extensions",
			"CommunityToolkit.WinUI.Helpers",
			"CommunityToolkit.WinUI.Triggers",
			"HarfBuzzSharp",
			"HarfBuzzSharp.NativeAssets.Android",
			"HarfBuzzSharp.NativeAssets.Linux",
			"HarfBuzzSharp.NativeAssets.Win32",
			"HarfBuzzSharp.NativeAssets.iOS",
			"HarfBuzzSharp.NativeAssets.macOS",
			"Microsoft.Bcl.AsyncInterfaces",
			"Microsoft.Extensions.Configuration",
			"Microsoft.Extensions.Configuration.Abstractions",
			"Microsoft.Extensions.Configuration.Binder",
			"Microsoft.Extensions.Configuration.CommandLine",
			"Microsoft.Extensions.Configuration.EnvironmentVariables",
			"Microsoft.Extensions.Configuration.FileExtensions",
			"Microsoft.Extensions.Configuration.Json",
			"Microsoft.Extensions.Configuration.UserSecrets",
			"Microsoft.Extensions.DependencyInjection",
			"Microsoft.Extensions.DependencyInjection.Abstractions",
			"Microsoft.Extensions.Diagnostics",
			"Microsoft.Extensions.Diagnostics.Abstractions",
			"Microsoft.Extensions.FileProviders.Abstractions",
			"Microsoft.Extensions.FileProviders.Physical",
			"Microsoft.Extensions.FileSystemGlobbing",
			"Microsoft.Extensions.Hosting",
			"Microsoft.Extensions.Hosting.Abstractions",
			"Microsoft.Extensions.Http",
			"Microsoft.Extensions.Localization.Abstractions",
			"Microsoft.Extensions.Logging",
			"Microsoft.Extensions.Logging.Abstractions",
			"Microsoft.Extensions.Logging.Configuration",
			"Microsoft.Extensions.Logging.Console",
			"Microsoft.Extensions.Logging.Debug",
			"Microsoft.Extensions.Logging.EventLog",
			"Microsoft.Extensions.Logging.EventSource",
			"Microsoft.Extensions.Options",
			"Microsoft.Extensions.Options.ConfigurationExtensions",
			"Microsoft.Extensions.Primitives",
			"Microsoft.NET.ILLink.Tasks",
			"Microsoft.Windows.CsWin32",
			"Microsoft.Xaml.Behaviors.WinUI.Managed",
			"Newtonsoft.Json",
			"Refit",
			"SkiaSharp",
			"SkiaSharp.NativeAssets.Android",
			"SkiaSharp.NativeAssets.Linux",
			"SkiaSharp.NativeAssets.WebAssembly",
			"SkiaSharp.NativeAssets.Win32",
			"SkiaSharp.NativeAssets.WinUI",
			"SkiaSharp.NativeAssets.iOS",
			"SkiaSharp.NativeAssets.macOS",
			"SkiaSharp.Resources",
			"SkiaSharp.SceneGraph",
			"SkiaSharp.Skottie",
			"SkiaSharp.Views",
			"SkiaSharp.Views.Uno.WinUI",
			"SkiaSharp.Views.WinUI",
			"System.Diagnostics.EventLog",
			"System.Json",
			"System.Runtime.InteropServices.NFloat.Internal",
			"Tmds.DBus.Protocol",
			"MZikmund.Toolkit.WinUI",
			"sqlite-net-e",
		]),

		new("Apache-2.0", "https://www.apache.org/licenses/LICENSE-2.0",
		[
			"SQLitePCLRaw.config.e_sqlite3",
			"SQLitePCLRaw.core",
			"SQLitePCLRaw.provider.e_sqlite3",
			"SQLitePCLRaw.provider.internal",
			"Uno.Core.Extensions.Collections",
			"Uno.Core.Extensions.Disposables",
			"Uno.Core.Extensions.Equality",
			"Uno.Core.Extensions.Logging",
			"Uno.Core.Extensions.Logging.Singleton",
			"Uno.Extensions.Configuration",
			"Uno.Extensions.Core",
			"Uno.Extensions.Core.WinUI",
			"Uno.Extensions.Hosting",
			"Uno.Extensions.Hosting.WinUI",
			"Uno.Extensions.Http",
			"Uno.Extensions.Localization",
			"Uno.Extensions.Localization.WinUI",
			"Uno.Extensions.Logging.OSLog",
			"Uno.Extensions.Serialization",
			"Uno.Extensions.Serialization.Http",
			"Uno.Extensions.Serialization.Refit",
			"Uno.Extensions.Storage",
			"Uno.Extensions.Storage.WinUI",
			"Uno.Fonts.Fluent",
			"Uno.Fonts.OpenSans",
			"Uno.Foundation",
			"Uno.Foundation.Logging",
			"Uno.Themes.WinUI",
			"Uno.Toolkit",
			"Uno.Toolkit.WinUI",
			"Uno.UI.Adapter.Microsoft.Extensions.Logging",
			"Uno.WinRT",
			"Uno.WinUI",
			"Uno.WinUI.DevServer.Messaging",
			"Uno.WinUI.Graphics2DSK",
			"Uno.WinUI.Lottie",
			"Uno.WinUI.Runtime.Skia",
			"Uno.WinUI.Runtime.Skia.Android",
			"Uno.WinUI.Runtime.Skia.AppleUIKit",
			"Uno.WinUI.Runtime.Skia.Linux.FrameBuffer",
			"Uno.WinUI.Runtime.Skia.MacOS",
			"Uno.WinUI.Runtime.Skia.Win32",
			"Uno.WinUI.Runtime.Skia.Wpf",
			"Uno.WinUI.Runtime.Skia.X11",
		]),

		// Android support-library bindings: the binding code is MIT, the bound library Apache-2.0.
		new("MIT AND Apache-2.0", null,
		[
			"Xamarin.AndroidX.Activity",
			"Xamarin.AndroidX.Annotation",
			"Xamarin.AndroidX.Annotation.Experimental",
			"Xamarin.AndroidX.Annotation.Jvm",
			"Xamarin.AndroidX.AppCompat",
			"Xamarin.AndroidX.AppCompat.AppCompatResources",
			"Xamarin.AndroidX.Arch.Core.Common",
			"Xamarin.AndroidX.Arch.Core.Runtime",
			"Xamarin.AndroidX.AsyncLayoutInflater",
			"Xamarin.AndroidX.Browser",
			"Xamarin.AndroidX.CardView",
			"Xamarin.AndroidX.Collection",
			"Xamarin.AndroidX.Collection.Jvm",
			"Xamarin.AndroidX.Concurrent.Futures",
			"Xamarin.AndroidX.ConstraintLayout",
			"Xamarin.AndroidX.ConstraintLayout.Core",
			"Xamarin.AndroidX.CoordinatorLayout",
			"Xamarin.AndroidX.Core",
			"Xamarin.AndroidX.Core.Core.Ktx",
			"Xamarin.AndroidX.Core.SplashScreen",
			"Xamarin.AndroidX.Core.ViewTree",
			"Xamarin.AndroidX.CursorAdapter",
			"Xamarin.AndroidX.CustomView",
			"Xamarin.AndroidX.CustomView.PoolingContainer",
			"Xamarin.AndroidX.DocumentFile",
			"Xamarin.AndroidX.DrawerLayout",
			"Xamarin.AndroidX.DynamicAnimation",
			"Xamarin.AndroidX.Emoji2",
			"Xamarin.AndroidX.Emoji2.ViewsHelper",
			"Xamarin.AndroidX.Fragment",
			"Xamarin.AndroidX.Interpolator",
			"Xamarin.AndroidX.Legacy.Support.Core.UI",
			"Xamarin.AndroidX.Legacy.Support.Core.Utils",
			"Xamarin.AndroidX.Legacy.Support.V4",
			"Xamarin.AndroidX.Lifecycle.Common",
			"Xamarin.AndroidX.Lifecycle.Common.Jvm",
			"Xamarin.AndroidX.Lifecycle.LiveData.Core",
			"Xamarin.AndroidX.Lifecycle.Process",
			"Xamarin.AndroidX.Lifecycle.Runtime",
			"Xamarin.AndroidX.Lifecycle.Runtime.Android",
			"Xamarin.AndroidX.Lifecycle.ViewModel",
			"Xamarin.AndroidX.Lifecycle.ViewModel.Android",
			"Xamarin.AndroidX.Lifecycle.ViewModelSavedState",
			"Xamarin.AndroidX.Lifecycle.ViewModelSavedState.Android",
			"Xamarin.AndroidX.Loader",
			"Xamarin.AndroidX.LocalBroadcastManager",
			"Xamarin.AndroidX.Media",
			"Xamarin.AndroidX.Print",
			"Xamarin.AndroidX.ProfileInstaller.ProfileInstaller",
			"Xamarin.AndroidX.RecyclerView",
			"Xamarin.AndroidX.ResourceInspection.Annotation",
			"Xamarin.AndroidX.SavedState",
			"Xamarin.AndroidX.SavedState.SavedState.Android",
			"Xamarin.AndroidX.SlidingPaneLayout",
			"Xamarin.AndroidX.Startup.StartupRuntime",
			"Xamarin.AndroidX.SwipeRefreshLayout",
			"Xamarin.AndroidX.Tracing.Tracing",
			"Xamarin.AndroidX.Tracing.Tracing.Android",
			"Xamarin.AndroidX.Transition",
			"Xamarin.AndroidX.VectorDrawable",
			"Xamarin.AndroidX.VectorDrawable.Animated",
			"Xamarin.AndroidX.VersionedParcelable",
			"Xamarin.AndroidX.ViewPager",
			"Xamarin.AndroidX.ViewPager2",
			"Xamarin.AndroidX.Window",
			"Xamarin.AndroidX.Window.Extensions.Core.Core",
			"Xamarin.Google.Android.Material",
			"Xamarin.Google.ErrorProne.Annotations",
			"Xamarin.Google.Guava.ListenableFuture",
			"Xamarin.JSpecify",
			"Xamarin.Jetbrains.Annotations",
			"Xamarin.Kotlin.StdLib",
			"Xamarin.KotlinX.AtomicFU",
			"Xamarin.KotlinX.AtomicFU.Jvm",
			"Xamarin.KotlinX.Coroutines.Android",
			"Xamarin.KotlinX.Coroutines.Core",
			"Xamarin.KotlinX.Coroutines.Core.Jvm",
			"Xamarin.KotlinX.Serialization.Core",
			"Xamarin.KotlinX.Serialization.Core.Jvm",
		]),

		new("Public domain", "https://sqlite.org/copyright.html",
		[
			"SourceGear.sqlite3",
		]),

		new("LGPL-2.1-or-later", "https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html",
		[
			"LibVLCSharp",
		]),

		new("Microsoft Public License (MS-PL)", "https://opensource.org/licenses/MS-PL",
		[
			"CommonServiceLocator",
		]),

		new("Microsoft software licence terms", "https://github.com/microsoft/WindowsAppSDK",
		[
			"Microsoft.Web.WebView2",
			"Microsoft.WindowsAppSDK",
		]),

		// These packages ship no <license> element; Uno Platform publishes its components
		// under Apache-2.0.
		new("Licence not declared by the package (Uno Platform, Apache-2.0 upstream)", "https://github.com/unoplatform/uno",
		[
			"Uno.Diagnostics.Eventing",
			"Uno.Fonts.Roboto",
			"Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI",
			"Uno.Microsoft.Xaml.Behaviors.WinUI.Managed",
			"Uno.Wasm.WebSockets",
			"Uno.icu-ios",
			"Uno.icu-macos",
			"Uno.icu-win",
		]),
	];

	/// <summary>
	/// Fonts and artwork bundled with the app.
	/// </summary>
	public static IReadOnlyList<ThirdPartyNotice> Assets { get; } =
	[
		new(
			"Inter (Inter-Light.ttf, 4.001)",
			"SIL Open Font License 1.1",
			"Copyright 2016 The Inter Project Authors",
			"https://scripts.sil.org/OFL"),
		new(
			"Event background photographs",
			"Public domain",
			"Nine bundled backgrounds sourced from PublicDomainPictures.net",
			"https://www.publicdomainpictures.net/"),
	];
}
